### ISSUE TITLE
Implement Travelling salesman problem solution using DP with bit-mask

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Dynamic-programming#1]
**the travelling salesman problem asks the following question:**
```
 "Given a list of cities and the distances between each pair of cities, 
what is the shortest possible route that visits each city exactly once and 
returns to the origin city?" 
```
[wiki](https://en.wikipedia.org/wiki/Travelling_salesman_problem)

### Note: Read [README](https://github.com/metoop/metoop/Dynamic-programming/blob/main/README.md) carefully.

**Comment by himanisuthar** [comment]
@sutharp777  i want to work on this issue
