### ISSUE TITLE
Knapsack 2 AtCoder Dp Contest

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Dynamic-programming#11]
_Time Limit: 2 sec / Memory Limit: 1024 MB_ **Score : 100** points

#### Problem Statement
```text
There are N
items, numbered 1,2,…,N. For each i (1≤i≤N), Item i has a weight of wi and a value of vi
```
```text
Taro has decided to choose some of the N
items and carry them home in a knapsack. The capacity of the knapsack is W, which means that the 
sum of the weights of items taken must be at most W

Find the maximum possible sum of the values of items that Taro takes home.
```
#### Constraints
```
    All values in input are integers.
    1≤N≤100

1≤W≤109
1≤wi≤W
1≤vi≤103
```
### Input

Input is given from Standard Input in the following format:
```
N W
w1  v1
w2 v2
:
wN vN
```

### Output
```
Print the maximum possible sum of the values of items that Taro takes home.
```
#### Sample Input 1
```
3 8
3 30
4 50
5 60
```
#### Sample Output 1
```
90
```
Items 1
and 3 should be taken. Then, the sum of the weights is 3+5=8, and the sum of the values is 30+60=90.

#### Sample Input 2
```
1 1000000000
1000000000 10
```
#### Sample Output 2
```
10
```
#### Sample Input 3

```
6 15
6 5
5 6
6 4
6 6
3 5
7 2
```
#### Sample Output 3
```
17
```
Items 2,4
and 5 should be taken. Then, the sum of the weights is 5+6+3=14, and the sum of the values is 6+6+5=17.
##### note you should pass all the test case of [Atcoder dp](https://atcoder.jp/contests/dp/tasks/dp_e)

**Comment by yaduvanshi777** [comment]
i want work on this please assign to me please..
