### ISSUE TITLE
Ugly Number

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Dynamic-programming#18]
```text
Write a program to check whether a given number is an ugly number.
Ugly numbers are positive numbers whose prime factors only include 2, 3, 5.
```

### Input:
 ```6```
### Output: 
```true```
### Explanation: 
```6 = 2 × 3```

### Input: 
```8```
### Output: 
```true```
### Explanation: 
```8 = 2 × 2 × 2```

### Input: 
```14```
### Output: 
```false``` 
### Explanation: 
```14 is not ugly since it includes another prime factor 7.```

Note:

   - 1 is typically treated as an ugly number.
   - Input is within the 32-bit signed integer range: [−231,  231 − 1].
   - read **README.md** carefully.
   - your code should pass all the test case on [leetcode](https://leetcode.com/problems/ugly-number/).

**Comment by siddhhu** [comment]
Hello want to work on this
