### ISSUE TITLE
Longest Palindromic Subsequence in C++

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Dynamic-programming#6]
```Given a string s, find the longest palindromic subsequence's length in s. 
You may assume that the maximum length of s is 1000.
```
### Example 1:
Input:

"bbbab"

Output:

4

One possible longest palindromic subsequence is "bbbb".

 

### Example 2:
Input:

"cbbd"

Output:

2

One possible longest palindromic subsequence is "bb".

 

### Constraints:

    1 <= s.length <= 1000
    s consists only of lowercase English letters.

**Note read README file carefully

**Comment by yaduvanshi777** [comment]
I want work on this issue please assign to me
