### ISSUE TITLE
Matrix Chain Multiplication

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Dynamic-programming#7]
```Given a sequence of matrices, we want to find the most efficient way to multiply these matrices together to obtain the minimum number of multiplications. The problem is not actually to perform the multiplication of the matrices but to obtain the minimum number of multiplications.
We have many options because matrix multiplication is an associative operation, meaning that the order in which we multiply does not matter. The optimal order depends only on the dimensions of the matrices.
The brute-force algorithm is to consider all possible orders and take the minimum. This is a very inefficient method.
Implement the minimum multiplication algorithm using dynamic programming.
```
### Input Format

The input file must contain the dimensions of the matrices each on a separate line.

### Constraints

Input should consist of positive integers.

### Output Format

The output file must contain the minimum number of multiplications needed to multiply the matrices as an integer.

### Sample Input
```
20  
2  
30  
12  
8
```
### Sample Output
```
1232
```
##### The above input and output samples correspond to the multiplication of these four matrices:
**A1 (20x2) * A2 (2x30) * A3 (30x12) * A4 (12x8)**
note : **read readme.md carefully**

**Comment by pradeexsu** [comment]
your code should pass [HackerRank test case](https://www.hackerrank.com/contests/programming-jam-2-0/challenges/matrix-chain-multiplication/problem)

**Comment by almas33** [comment]
please assign this issue to me

**Comment by pradeexsu** [comment]
@almas33 read readme carefully

**Comment by pradeexsu** [comment]
go ahead
