### ISSUE TITLE
KNAPSACK - The Knapsack Problem

### ISSUE THREAD

**Issue by pradeexsu** [metoop/Dynamic-programming#8]
The famous knapsack problem. You are packing for a vacation on the sea side and you are going to carry only one bag with capacity S (1 <= S <= 2000). You also have N (1<= N <= 2000) items that you might want to take with you to the sea side. Unfortunately you can not fit all of them in the knapsack so you will have to choose. For each item you are given its size and its value. You want to maximize the total value of all the items you are going to bring. What is this maximum total value?

### Input
On the first line you are given S and N. N lines follow with two integers on each line describing one of your items. 
The first number is the size of the item and the next is the value of the item.
### Output

You should output a single integer on one like - the total maximum value from the best choice of items for your trip.
### Example

```text
Input:
4 5
1 8
2 4
3 0
2 5
2 3


Output:
13
```
**make sure your code should pass all the testcase of [spoj](https://www.spoj.com/problems/KNAPSACK/)**
note : **please read readme.md file carefully**

**Comment by yaduvanshi777** [comment]
I want on this issue please assign to me
